-- MySQL Script generated by MySQL Workbench
-- Tue Apr  9 23:35:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema codebox
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `codebox` ;

-- -----------------------------------------------------
-- Schema codebox
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codebox` DEFAULT CHARACTER SET utf8 ;
USE `codebox` ;

-- -----------------------------------------------------
-- Table `codebox`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codebox`.`usuario` ;

CREATE TABLE IF NOT EXISTS `codebox`.`usuario` (
  `email` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `a_paterno` VARCHAR(45) NOT NULL,
  `a_materno` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `codebox`.`principal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codebox`.`principal` ;

CREATE TABLE IF NOT EXISTS `codebox`.`principal` (
  `id_principal` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL DEFAULT 'Raiz',
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_principal`),
  INDEX `fk_principal_usuario1_idx` (`usuario_email` ASC)  ,
  CONSTRAINT `fk_principal_usuario1`
    FOREIGN KEY (`usuario_email`)
    REFERENCES `codebox`.`usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `codebox`.`carpeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codebox`.`carpeta` ;

CREATE TABLE IF NOT EXISTS `codebox`.`carpeta` (
  `id_carpeta` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `principal_id_principal` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_carpeta`),
  INDEX `fk_carpeta_principal1_idx` (`principal_id_principal` ASC)  ,
  CONSTRAINT `fk_carpeta_principal1`
    FOREIGN KEY (`principal_id_principal`)
    REFERENCES `codebox`.`principal` (`id_principal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `codebox`.`subcarpeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codebox`.`subcarpeta` ;

CREATE TABLE IF NOT EXISTS `codebox`.`subcarpeta` (
  `id_subcarpeta` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `carpeta_id_carpeta` INT(11) NOT NULL,
  PRIMARY KEY (`id_subcarpeta`),
  INDEX `fk_subcarpeta_carpeta_idx` (`carpeta_id_carpeta` ASC)  ,
  CONSTRAINT `fk_subcarpeta_carpeta`
    FOREIGN KEY (`carpeta_id_carpeta`)
    REFERENCES `codebox`.`carpeta` (`id_carpeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `codebox`.`archivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codebox`.`archivo` ;

CREATE TABLE IF NOT EXISTS `codebox`.`archivo` (
  `id_Archivo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` MEDIUMTEXT NULL DEFAULT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  `dato` MEDIUMBLOB NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `subcarpeta_id_subcarpeta` INT(11) NULL DEFAULT NULL,
  `carpeta_id_carpeta` INT(11) NULL DEFAULT NULL,
  `principal_id_principal` INT(11) NOT NULL,
  PRIMARY KEY (`id_Archivo`),
  INDEX `fk_archivo_subcarpeta1_idx` (`subcarpeta_id_subcarpeta` ASC)  ,
  INDEX `fk_archivo_carpeta1_idx` (`carpeta_id_carpeta` ASC)  ,
  INDEX `fk_archivo_principal1_idx` (`principal_id_principal` ASC)  ,
  CONSTRAINT `fk_archivo_carpeta1`
    FOREIGN KEY (`carpeta_id_carpeta`)
    REFERENCES `codebox`.`carpeta` (`id_carpeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_archivo_principal1`
    FOREIGN KEY (`principal_id_principal`)
    REFERENCES `codebox`.`principal` (`id_principal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_archivo_subcarpeta1`
    FOREIGN KEY (`subcarpeta_id_subcarpeta`)
    REFERENCES `codebox`.`subcarpeta` (`id_subcarpeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `codebox`.`carpeta_compartida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codebox`.`carpeta_compartida` ;

CREATE TABLE IF NOT EXISTS `codebox`.`carpeta_compartida` (
  `id_carpeta` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_carpeta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `codebox`.`archivo_compartido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codebox`.`archivo_compartido` ;

CREATE TABLE IF NOT EXISTS `codebox`.`archivo_compartido` (
  `id_Archivo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` MEDIUMTEXT NULL DEFAULT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  `dato` LONGBLOB NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `carpeta_compartida_id_carpeta` INT(11) NOT NULL,
  PRIMARY KEY (`id_Archivo`),
  INDEX `fk_archivo_compartido_carpeta_compartida1_idx` (`carpeta_compartida_id_carpeta` ASC)  ,
  CONSTRAINT `fk_archivo_compartido_carpeta_compartida1`
    FOREIGN KEY (`carpeta_compartida_id_carpeta`)
    REFERENCES `codebox`.`carpeta_compartida` (`id_carpeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `codebox`.`carpeta_compartida_has_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codebox`.`carpeta_compartida_has_usuario` ;

CREATE TABLE IF NOT EXISTS `codebox`.`carpeta_compartida_has_usuario` (
  `carpeta_compartida_id_carpeta` INT(11) NOT NULL,
  `usuario_email` VARCHAR(100) NOT NULL,
  `permiso` INT(11) NOT NULL,
  INDEX `fk_carpeta_compartida_has_usuario_usuario1_idx` (`usuario_email` ASC)  ,
  INDEX `fk_carpeta_compartida_has_usuario_carpeta_compartida1_idx` (`carpeta_compartida_id_carpeta` ASC)  ,
  CONSTRAINT `fk_carpeta_compartida_has_usuario_carpeta_compartida1`
    FOREIGN KEY (`carpeta_compartida_id_carpeta`)
    REFERENCES `codebox`.`carpeta_compartida` (`id_carpeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carpeta_compartida_has_usuario_usuario1`
    FOREIGN KEY (`usuario_email`)
    REFERENCES `codebox`.`usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `codebox`.`notificaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codebox`.`notificaciones` ;

CREATE TABLE IF NOT EXISTS `codebox`.`notificaciones` (
  `id_notificacion` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_u` VARCHAR(55) NOT NULL,
  `nota` VARCHAR(255) NOT NULL,
  `nombre_ca` VARCHAR(55) NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_notificacion`),
  INDEX `fk_Notificaciones_usuario1_idx` (`usuario_email` ASC)  ,
  CONSTRAINT `fk_Notificaciones_usuario1`
    FOREIGN KEY (`usuario_email`)
    REFERENCES `codebox`.`usuario` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `codebox`.`comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `codebox`.`comentario` ;

CREATE TABLE IF NOT EXISTS `codebox`.`comentario` (
  `id_Comentario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `mensaje` MEDIUMTEXT NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  `dato` LONGBLOB NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `carpeta_compartida_id_carpeta` INT(11) NOT NULL,
  `nombre_u` VARCHAR(45) NOT NULL,
  `a_paterno_u` VARCHAR(45) NOT NULL,
  `a_materno_u` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Comentario`),
  INDEX `fk_comentario_carpeta_compartida1_idx` (`carpeta_compartida_id_carpeta` ASC)  ,
  CONSTRAINT `fk_comentario_carpeta_compartida1`
    FOREIGN KEY (`carpeta_compartida_id_carpeta`)
    REFERENCES `codebox`.`carpeta_compartida` (`id_carpeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
